modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="fumo"
version="15.0.0"
displayName="Fumo"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://modrinth.com/mod/fumo"
logoFile="logo.png"
authors="VegaKey"
description="Adds Fumos from Touhou."

[[dependencies.fumo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




